### ISSUE TITLE
Kleingruppen Ort and Zeit

### ISSUE THREAD

**Issue by MichaelGSP** [ecclesianuernberg/genesis#20]
Treffzeit sound wired to me. Maybe I am wrong but 

Ort des Treffens (to be consistent)
Zeit des Treffens

May sound a little bit better.

**Comment by xsteadfastx** [comment]
treffzeit ist das was in churchtools drin steht. deswegen habe ich es übernommen

**Comment by MichaelGSP** [comment]
Ah ok. Dann gefällt es mir auf CT auch nicht :D

**Comment by xsteadfastx** [comment]
On Wed, 15. Apr 02:30, MichaelGSP wrote:

> Ah ok. Dann gefällt es mir auf CT auch nicht :D

naja schlag was vor und ich baue es ein :)

**Comment by MichaelGSP** [comment]
Vorschlag :)
Ort des Treffens
Zeit des Treffens
