### ISSUE TITLE
!Search restriction

### ISSUE THREAD

**Issue by MichaelGSP** [ecclesianuernberg/genesis#25]
I shouldn't see any names from the database via search when I am not logged in. I can't access the people, but I see their full names! This is a big privacy issue and should be fixed soon.

---

The search feature is awesome btw!

**Comment by MichaelGSP** [comment]
Ok, this is wired. I tried to do it again. Now, once I access Genesis, the login screen pops up immediately. Before I was able to see the page, without logging in. Just after clicking a name I searched for the login screen appeared.

Was ich gemacht habe:
Ich hab auf den API Link in deiner Mail geklickt. Der Browser hat mich nach meinen Logikdaten gefragt (Safari, nicht die Seite). Danach wurde mir der Text ausgegeben den du auch in der Email gezeigt hast. Von dieser Seite bin ich direkt zur Startseite. Diese war voll sichtbar, ich hab die Suche benutzt, die Namen wurden angezeigt, beim Klick auf den Namen wurde aber dann wieder der Login Screen (diesmal von Genesis) angezeigt, so als ob ich nicht eingeloggt bin.

**Comment by xsteadfastx** [comment]
On Tue, 12. May 02:31, MichaelGSP wrote:

> I shouldn't see any names from the database via search when I am not logged in.
> I can't access the people, but I see their full names! This is a big privacy
> issue and should be fixed soon.

suche geht nur wenn eingeloggt.

**Comment by MichaelGSP** [comment]
Kann es auch nicht mehr reproduzieren. Komisch...

**Comment by xsteadfastx** [comment]
On Tue, 12. May 02:38, MichaelGSP wrote:

> Kann es auch nicht mehr reproduzieren. Komisch...

die suchmaske ist für uneingeloggte noch nicht einmal sichtbar.
