### ISSUE TITLE
Prayer Request - name and full name option

### ISSUE THREAD

**Issue by MichaelGSP** [ecclesianuernberg/genesis#4]
There should be two options when posting a prayer request
1. Full name (Name anzeigen)
2. if selected: 2. Just the first name (Nur Vorname anzeigen)

**Comment by xsteadfastx** [comment]
also mal eine idee.... garnichts zum aktivieren sondern einfach ein feld mit dem titel "namen". da kann man reinschreiben was man will. angezeigt wird dann das... in der db wird es aber unter dem bestimmten user gespeichert.

**Comment by MichaelGSP** [comment]
Hört sich nach einer guten Idee an!
