### ISSUE TITLE
Switch Prayer

### ISSUE THREAD

**Issue by MichaelGSP** [ecclesianuernberg/genesis#6]
When I click "Neues Anliegen" it happened that it shows the same for several clicks until it switched to the next one.

It shouldn't be the same request after clicking the button.

**Comment by xsteadfastx** [comment]
das geht alles per random. also bei wenigen gebeten gibt es da auch noch wenig auswahl zum randomisieren :)

**Comment by MichaelGSP** [comment]
Könnte es aber dennoch passieren, dass bei 100 anliegen durch random das gleiche nochmal angezeigt wird?
Ist zwar kein Beinbruch, könnte aber als Bug wahrgenommen werden.

**Comment by xsteadfastx** [comment]
ich sehe das nicht so daramatisch irgendwie. sonst kommt eine menge logik wieder dazu. und so ist es random... also vielleicht zweimal beten :)

**Comment by MichaelGSP** [comment]
:D ok!
